spring:
  datasource:
    # url: jdbc:postgresql://localhost:5432/mytest
    # url: jdbc:postgresql://localhost:1235/mytest
    url: jdbc:postgresql://postgres-build-vp:5432/mytest # postgres container name
    username: umalak # postgres
    password: password # malak1
    driver-class-name : org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
